version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dud2"
s3_bucket = "superbucketforall"
s3_prefix = "dud2"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppId=\"1\""
